#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_page.html
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    server_name 54.89.73.205;

    root /var/www/html;
    index index.html;
    error_page 404 /404_page.html;

    location = /404_page.html {
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
sudo service nginx restart
