#!/usr/bin/env bash
# Loops in 10 places displaying "bad luck" "good luck" "Best School" on 4th, 8th and other iterations respectively
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
