#!/usr/bin/env bash
# script displays numbers 1 to 20 and 4, 9, 17 represented by "bad luck from China", "bad luck from Japan" and "bad luck from Italy" respectively
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
		4)
		echo "bad luck from China"
		;;
		9)
                echo "bad luck from Japan"
		;;
		17)
                echo "bad luck from Italy"
	esac
	i=$((i+1))
done
