#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo ufw allow 8080/tcp
sudo tee /etc/nginx/nginx.conf > /dev/null <<EOF
user nginx;
EOF
sudo service nginx restart
