#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo ufw allow 8080/tcp
sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 8080;
}
EOF
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo chown -R nginx:nginx /var/www/html
sudo service nginx restart
